// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHF8nQ5HWOMzmcEkcwCUVFOUzpc-UHZhI',
    appId: '1:121715619546:android:7746aef0be3c16fd8d97e3',
    messagingSenderId: '121715619546',
    projectId: 'bookease-39d4d',
    storageBucket: 'bookease-39d4d.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJGBNrM8WiOK5Htf49xLMLNZmyefuH9lI',
    appId: '1:121715619546:web:b853ea1abc9bd7de8d97e3',
    messagingSenderId: '121715619546',
    projectId: 'bookease-39d4d',
    authDomain: 'bookease-39d4d.firebaseapp.com',
    storageBucket: 'bookease-39d4d.firebasestorage.app',
    measurementId: 'G-R9S388ZTLT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU80mf7-99REVYpJZSqWgvXbcV3XoxmPg',
    appId: '1:121715619546:ios:688f90720e0231708d97e3',
    messagingSenderId: '121715619546',
    projectId: 'bookease-39d4d',
    storageBucket: 'bookease-39d4d.firebasestorage.app',
    androidClientId: '121715619546-nai11aeup2dljiua7n6nfgrraovstpf5.apps.googleusercontent.com',
    iosClientId: '121715619546-vemtak6gaubr0sgs205oavmka4m86b6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointmentBooking',
  );
}
